# Site settings 配置站点
title: 'kambits'
description: 'A little study will make a big process.'
keywords: 'blockchain, ethereum, quorum, python'
url: 'https://kambits.com' # your host

# nav 中文字符空格：&emsp;
nav: # 最佳体验 六个标签 且最好每个标签不超过4中文字
  首页: '/'
  标签: '/tags.html'
  时间线: '/timeline.html'
  应用推荐: '/applications.html'
  关于博主: '/about.html'
  # 友情链接: '/friendLink.html'

# 博主
author: true
name: 'kambits'
NickName: 'kambits'
webtitle: 'kambits'
bio: 'A little study will make a big process.'
about: true
aboutyou: '喜欢编程的娃, 目前在做和区块链开发相关的项目(以太坊，Quorum), 同时也在学习编程相关知识.'
portraits: '/assets/profile.jpeg' # your portraits image file path

# SNS
SNS: true
SNS-icon: #['Facebook', 'weibo', 'qq', 'github', 'Dribbble', 'Twitter', 'instagram', 'weixin', 'Codepen', 'Google', 'zhihu', 'juejin', 'twitch', 'docker', 'segmentfault', 'csdn', 'jianshu', 'OSCHINA', 'toutiao', 'cnblogs']
  mail: 'mailto:kambits.dev@gmail.com'
  github: 'https://github.com/kambits'
  docker: 'https://hub.docker.com/u/kambits'
  juejin: 'https://juejin.im/user/5d975cb8e51d4577e86d0d89'
  segmentfault: 'https://segmentfault.com/u/kambits'
  csdn: 'https://blog.csdn.net/sinat_38431275'
  zhihu: 'https://www.zhihu.com/people/kambits/'
  OSCHINA: 'https://my.oschina.net/kambits'
  # toutiao: ''
  cnblogs: 'https://www.cnblogs.com/kambits/'
  # weixin: '' # 你的微信二维码存放的地址
  # qq: '' # 你的qq二维码存放的地址 or http://wpa.qq.com/msgrd?v=3&uin='你的QQ号'&site=qq&menu=yes
  # Codepen: ''
  # weibo: ''
  # instagram: ''
  # Twitter: ''
  # Dribbble: ''
  # Facebook: ''
  # Google: ''
  # twitch: ''

  

# 分页
paginate: 20
paginatepath: ['page:num']

# since
footer:
  since: 2019

# Markdown
markdown: kramdown
kramdown:
  input: GFM
# 代码高亮 使用rouge
highlighter: rouge
# 代码高亮主题使用pygments主题: autumn\ default\ emacs\ friendly\ manni\ murphy\ pastie\ perldoc\ tango 任选一个你喜欢的主题名称填在下面的单引号中
pygmentsTheme: 'default'

# 友情链接
friends:
  jekyll: 'https://www.jekyll.com.cn/'
  google: 'https://www.google.com'
  


# 评论 最佳体验 在disqus、livere和Gitment之间三选一
# disqus 评论
disqus: false
disqus_url: '' # https://abc.disqus.com/embed.js
# 来必力评论
livere: true
livere_uid: 'MTAyMC80Njk3Ny8yMzQ3OA==' # MTAyMC8zNDI2OS8xMDgwNg==
# Gitment评论 OAuth Application
Gitment: false
Gitment_owner: ''  # github用户名
Gitment_repo: ''  # github博客存放的仓库名
client_id: ''  # 注册 OAuth Application 后获得的 client_id
client_secret: ''  # 注册 OAuth Application 后获得的 client_secret

# Share : weibo, qq, wechat, tencent, douban, qzone, linkedin, diandian, facebook, twitter, google
social-share: true
social-share-items: ['qq', 'wechat', 'weibo', 'twitter', 'facebook']

# 百度统计 在baidu-url里填写自己相关的url代码
baidu: false
baidu-url: ''
# 谷歌分析 在google-ID里填写自己在谷歌分析获得的追踪ID
google: true
google-ID: 'UA-149588658-1'

# 博客头信息备选颜色（该部分在站点中不充当站点变量，将其写在post的头信息中用来充当页面变量）
color: rgb(154,133,255) rgb(255,90,90) rgb(255,210,32) rgb(98,170,255)

applications:
  vscode:
    link: "https://www.google.com"
    description: "Visual Studio Code（简称VS Code）是一个由微软开发，同时支持Windows 、 Linux和macOS等操作系统且开放源代码的代码编辑器[4],它支持测试，并内置了Git 版本控制功能，同时也具有开发环境功能，例如代码补全（类似于 IntelliSense）、代码片段和代码重构等，该编辑器支持用户个性化配置，例如改变主题颜色、键盘快捷方式等各种属性和参数，同时还在编辑器中内置了扩展程序管理的功能。"
  bear:
    link: "https://www.google.com"
    description: "bear"
