# Site settings 配置站点
title: 'kambits'
description: 'A little study will make a big process.'
keywords: 'blockchain, ethereum, quorum, python'
url: 'https://kambits.com' # your host

# nav 中文字符空格：&emsp;
nav: # 最佳体验 六个标签 且最好每个标签不超过4中文字
  首页: '/'
  标签: '/tags.html'
  时间线: '/timeline.html'
  应用推荐: '/applications.html'
  关于博主: '/about.html'
  # 友情链接: '/friendLink.html'

# 博主
author: true
name: 'kambits'
NickName: 'kambits'
webtitle: 'kambits'
bio: 'A little study will make a big process.'
about: true
aboutyou: '喜欢编程的娃, 目前在做和区块链开发相关的项目(以太坊，Quorum), 同时也在学习编程相关知识.'
portraits: '/assets/profile.jpeg' # your portraits image file path

# SNS
SNS: true
SNS-icon: #['Facebook', 'weibo', 'qq', 'github', 'Dribbble', 'Twitter', 'instagram', 'weixin', 'Codepen', 'Google', 'zhihu', 'juejin', 'twitch', 'docker', 'segmentfault', 'csdn', 'jianshu', 'OSCHINA', 'toutiao', 'cnblogs']
  mail: 'mailto:kambits.dev@gmail.com'
  github: 'https://github.com/kambits'
  docker: 'https://hub.docker.com/u/kambits'
  juejin: 'https://juejin.im/user/5d975cb8e51d4577e86d0d89/posts'
  segmentfault: 'https://segmentfault.com/u/kambits/articles'
  csdn: 'https://blog.csdn.net/sinat_38431275'
  zhihu: 'https://www.zhihu.com/people/kambits/posts'
  OSCHINA: 'https://my.oschina.net/kambits'
  toutiao: 'https://www.toutiao.com/c/user/3249784695825112/#mid=1646529547541507'
  cnblogs: 'https://www.cnblogs.com/kambits/'
  jianshu: 'https://www.jianshu.com/u/f5097af74bc8'
  weixin: 'https://image.kambit.cn/WechatIMG3.jpeg' # 你的微信二维码存放的地址
  # qq: '' # 你的qq二维码存放的地址 or http://wpa.qq.com/msgrd?v=3&uin='你的QQ号'&site=qq&menu=yes
  # Codepen: ''
  # weibo: ''
  # instagram: ''
  # Twitter: ''
  # Dribbble: ''
  # Facebook: ''
  # Google: ''
  # twitch: ''

  

# 分页
paginate: 20
paginatepath: ['page:num']

# since
footer:
  since: 2019

# Markdown
markdown: kramdown
kramdown:
  input: GFM
# 代码高亮 使用rouge
highlighter: rouge
# 代码高亮主题使用pygments主题: autumn\ default\ emacs\ friendly\ manni\ murphy\ pastie\ perldoc\ tango 任选一个你喜欢的主题名称填在下面的单引号中
pygmentsTheme: 'default'

# 友情链接
friends:
  jekyll: 'https://www.jekyll.com.cn/'
  
  


# 评论 最佳体验 在disqus、livere和Gitment之间三选一
# disqus 评论
disqus: false
disqus_url: '' # https://abc.disqus.com/embed.js
# 来必力评论
livere: true
livere_uid: 'MTAyMC80Njk3Ny8yMzQ3OA==' # MTAyMC8zNDI2OS8xMDgwNg==
# Gitment评论 OAuth Application
Gitment: false
Gitment_owner: ''  # github用户名
Gitment_repo: ''  # github博客存放的仓库名
client_id: ''  # 注册 OAuth Application 后获得的 client_id
client_secret: ''  # 注册 OAuth Application 后获得的 client_secret

# Share : weibo, qq, wechat, tencent, douban, qzone, linkedin, diandian, facebook, twitter, google
social-share: true
social-share-items: ['qq', 'wechat', 'weibo', 'twitter', 'facebook']

# 百度统计 在baidu-url里填写自己相关的url代码
baidu: false
baidu-url: ''
# 谷歌分析 在google-ID里填写自己在谷歌分析获得的追踪ID
google: true
google-ID: 'UA-149588658-1'

# 博客头信息备选颜色（该部分在站点中不充当站点变量，将其写在post的头信息中用来充当页面变量）
color: rgb(154,133,255) rgb(255,90,90) rgb(255,210,32) rgb(98,170,255)

applications:
  VScode:
    link: "https://www.google.com"
    description: "VScode 包含很多插件，常用插件sftp, remote-SSH, project manager."
  Typora:
    link: "https://www.typora.io/"
    description: "Typora 将「写字」和「预览」合并在一起，很容易在写Markdown的时候看到格式"
  Sourcetree:
    link: "https://www.sourcetreeapp.com/"
    description: "Sourcetree开电脑历史记录，我还是习惯命令行使用git."
  Iterm2:
    link: "https://www.iterm2.com"
    description: "自定义的terminal."
  Docker:
    link: "https://www.docker.com/"
    description: "容器."
  Navicat for MySql:
    link: "https://www.navicat.com/en/products/navicat-for-mysql"
    description: "MySql GUI, 很容易使用."
  Postman:
    link: "https://www.getpostman.com"
    description: "简单而强大的API调试工具."
  IthoughtsX:
    link: "https://www.toketaware.com/ithoughts-osx"
    description: "强大的思维导图软件."
  TeamViewer:
    link: "https://www.teamviewer.cn/cn/"
    description: "免费而好用的远程桌面软件."
  
